### ISSUE TITLE
Please Do Research about OutSourcing Industry

### ISSUE THREAD

**Issue by irufaan** [irufaan/team-kernel-competition#1]
The competition is closely related to the development of service outsourcing industry, and the content and review of the competition are concerned with technological innovation, application innovation, service innovation and so on.
Following are the areas need to do research about outsourcing industry

- [x] What and meaning of outsourcing Industry or Service?
- [x] What are the types of outsourcing?
- [x] What are the Outsourcing Examples or Companies present right now ?
- [x] What are  the business help as Software Company can give to OutSourcing Industry? What I mean is, making websites or making a mobile app before website or making a smart robot, so on? We need to find out what project we need to choose for this competition, website or mobile app?

**Comment by Nicole-Rutagengwa** [comment]
Alright ! @irufaan

**Comment by KingKlaus** [comment]
Okay great

**Comment by KingKlaus** [comment]
Lots of interesting projects

**Comment by Ricil** [comment]
Alright sir .

**Comment by Nicole-Rutagengwa** [comment]
what is outsoursing?
**Def**:
Outsourcing is a business practice in which a company hires another company or an individual to perform tasks, handle operations or provide services that are either usually executed or had previously been done by the company's own employees.
Companies today can outsource a number of tasks or services. They often outsource information technology services, including programming and application development as well as technical support. They frequently outsource customer service and call service functions.

Outsourcing business functions is sometimes called contracting out or business process outsourcing.

**Reasons for outsourcing:**
Companies often outsource as a way to lower costs, improve efficiencies and gain speed. Companies that decide to outsource rely on the third-party providers' expertise in performing the outsourced tasks to gain such benefits. The underlying principle is that because the third-party provider focuses on that particular task, it is able to do it better, faster and cheaper than the hiring company could.
Given such benefits, companies often decide to outsource supporting functions within their businesses so they can focus their resources more specifically on their core competencies, thereby helping them gain competitive advantages in the market.

However, some companies decide to outsource for other reasons. eg: they outsource because they're unable to hire in-house workers with the specialized skills and experience needed to perform certain jobs.
-Companies sometimes opt to outsource as a way to shift meeting regulatory requirements or obligations to the third-party provider.
Although outsourcing had been viewed as a way to lower costs and gain efficiencies, it is increasingly becoming a strategic tool for companies, too.

Click in the link below and this will make more clear that last point that irufan mentioned in the research to do...also this will show you how outsourcing is helpful for a software company.
[https://www.flatworldsolutions.com/articles/advantages-outsourcing-services.php]

**Comment by irufaan** [comment]
@Hasanzjnu @KingKlaus @Ricil Tomorrow is deadline for this task

**Comment by KingKlaus** [comment]
Will get it done tonight bro

**Comment by Ricil** [comment]
Alright sir

**Comment by Ricil** [comment]
Types of outsourcing.

1. IT outsourcing 
2. Multisourcing
3. Manufacturer outsourcing 
4. Process-specific outsourcing 
5. BPO
6. Project outsourcing 
7. Offshore outsourcing

**Comment by KingKlaus** [comment]
which one company contracts-out a part of existing internal activity to another company".[1] It involves the contracting out of a business process (e.g. payroll processing, claims processing) and operational, and/or non-core functions (e.g. manufacturing, facility management, call center support) to another party (see also business process outsourcing

**Comment by KingKlaus** [comment]
Professional Outsourcing. Professional Outsourcing includes accounting, legal, purchasing, information technology (IT), IT or administrative support and other specialized services. ...IT Outsourcing. ...Multisourcing. ...Manufacturer Outsourcing. ...Process-Specific Outsourcing. ...BPO. ...Project Outsourcing. ...Offshore Outsourcing.

**Comment by KingKlaus** [comment]
The kinds of outsourcing work performed vary widely across industry sectors.  Some common outsourcing activities include: human resource management, facilities management, supply chain management, accounting, customer support and service, marketing, computer aided design, research, design, content writing, engineering, diagnostic services, and legal documentation.

**Comment by irufaan** [comment]
Good Work for those who did the research,, I didnt see any contribution from @Hasanzjnu .. Sorry to say this im gonna close this task even though he didnt contribute.

**Comment by irufaan** [comment]
BUt no one recommended or said anything about what Software We suppose to do for our competition which is the last point of the research..  So,  im deciding myself to do website.

**Comment by Hasanzjnu** [comment]
I compiled this list of reasons why outsourcing Web design and development is advantageous:  
Competitive Environment: 
Because of the highly competitive nature of the Web development industry, Web development firms must perform at a very high level at all times in order to keep their clients satisfied.  This constant pressure to succeed, which produces outstanding results on client projects, rarely exists amongst in-house IT or marketing staff.

Cost Savings:
As you only pay for time used, outsourcing Web development frequently results in significant savings.

Economies of Scale:
In-house IT and marketing teams are frequently backed up and projects progress slowly.  A professional Web development firm will have the resources to start projects immediately and complete them quickly.

Better Service Quality:
As Web development is handled on a client/service provider basis, service tends to be better than that provided by in-house staff.

Better Risk Management:
Risks are reduced as the Web development partner will have prior knowledge and experience on projects and only offer proven working solutions. Not only will they have more real world experience, but they will also be better at mitigating the risks involved in handling delicate tasks like upgrades and security management.
 So from my perspective i think we should decide to make a website.
